### ISSUE TITLE
How to download specific nodes with  tome services

### ISSUE THREAD

**Issue by yuseferi** [drupal-tome/tome-project#11]
I wanted to use tome in my custom drupal cron job to get specific nodes ( specific book) periodically,

I found this code in the api page.
[https://tome.fyi/docs/technical/api/](https://tome.fyi/docs/technical/api/)

>Using the tome_static.generator service
Beyond what's documented in the [static generator's interface](https://git.drupalcode.org/project/tome/blob/8.x-1.x/modules/tome_static/src/StaticGeneratorInterface.php), it can be hard to know how to accurately generate static pages manually. Here's a documented code snippet that goes over almost everything the static command and form does

```
<?php

/** @var \Drupal\tome_static\StaticGeneratorInterface $static */
$static = \Drupal::service('tome_static.generator');

/** @var \Drupal\tome_static\RequestPreparer $request_preparer */
$request_preparer = \Drupal::service('tome_static.request_preparer');

// Prepare for a new request. This is necessary so that static caches in Drupal
// can be reset between multiple requests in one bootstrap.
$request_preparer->prepareForRequest();

// Request an arbitrary path. "$invoke_paths" at this point is anything that
// needs to be copied (an existing file) or requested (an image derivative,
// other paths, etc.)
$invoke_paths = $static->requestPath('/foo');

// Export paths will try to copy or remove as many paths as possible without
// making a new internal request.
$invoke_paths = $static->exportPaths($invoke_paths);

// The remaining invoke paths need to be handled in new requests.
foreach ($invoke_paths as $path) {
  // Since we are only trying to export one path, restrict new requests to
  // paths with extensions, which are probably RSS feeds and image derivatives.
  if (pathinfo($path, PATHINFO_EXTENSION)) {
    $request_preparer->prepareForRequest();
    // This could return more paths, but we're ignoring that for simplicity.
    $static->requestPath($path);
  }
}
```

it looks great but there is an issue with that. with this solution, I didn't find any `uri` parameter to let me change the urls of the downloaded file.

could you please tell me how can I define URI when I want to use tome service directly ( not in drush mode)?

**Comment by mortenson** [comment]
Good question @yuseferi - I think it's this:
```php
    $original_params = TomeStaticHelper::setBaseUrl($this->getRequest(), $base_url);

    $paths = $this->static->getPaths();

    TomeStaticHelper::restoreBaseUrl($this->getRequest(), $original_params);
```
From https://git.drupalcode.org/project/tome/-/blob/8.x-1.x/modules/tome_static/src/Form/StaticGeneratorForm.php#L154-158

Where `$this->getRequest()` returns the original request that initiated the state site build (if you run cron via Drush this may not be relevant), and `$base_url` is the `uri` you want to provide. The `tome_static_cron` sub-module should be a good reference for you as well, since it does something really close to this.

**Comment by yuseferi** [comment]
Hi @mortenson ,
Thank you very much for your reply, I'm really stuck on that and looking for another solution.

what had you mentioned is not clear for me , could you please explain further,

what I want is just replace all  origin host to my new host. ( for example http://localhost:8080)
I tried the following code ( it's the api sample suage + what you suggested) but unfortunately didn't work.

`
<?php

/** @var \Drupal\tome_static\StaticGeneratorInterface $static */
$static = \Drupal::service('tome_static.generator');

    $original_params = TomeStaticHelper::setBaseUrl($this->getRequest(), "http://localhost:8080");

    $paths = $this->static->getPaths();

    TomeStaticHelper::restoreBaseUrl($this->getRequest(), $original_params);
    
/** @var \Drupal\tome_static\RequestPreparer $request_preparer */
$request_preparer = \Drupal::service('tome_static.request_preparer');

// Prepare for a new request. This is necessary so that static caches in Drupal
// can be reset between multiple requests in one bootstrap.
$request_preparer->prepareForRequest();

// Request an arbitrary path. "$invoke_paths" at this point is anything that
// needs to be copied (an existing file) or requested (an image derivative,
// other paths, etc.)
$invoke_paths = $static->requestPath('/foo');

// Export paths will try to copy or remove as many paths as possible without
// making a new internal request.
$invoke_paths = $static->exportPaths($invoke_paths);

// The remaining invoke paths need to be handled in new requests.
foreach ($invoke_paths as $path) {
  // Since we are only trying to export one path, restrict new requests to
  // paths with extensions, which are probably RSS feeds and image derivatives.
  if (pathinfo($path, PATHINFO_EXTENSION)) {
    $request_preparer->prepareForRequest();
    // This could return more paths, but we're ignoring that for simplicity.
    $static->requestPath($path);
  }
}
`


could you please tell me how can I change all apperance of the origin host with my custom one in all HTML files?

**Comment by yuseferi** [comment]
I played with that and finally, this solution worked for me:


```
    /** @var \Drupal\tome_static\StaticGeneratorInterface $static */
    $static = \Drupal::service('tome_static.generator');

    /** @var \Drupal\tome_static\RequestPreparer $request_preparer */
    $request_preparer = \Drupal::service('tome_static.request_preparer');


    $path = '/en/viewport/EssDr/english/essential-drugs-16682376.html';
//    $invoke_paths = $static->requestPath($path);

    $base_url = "http://localhost:8080";

    $original_params = TomeStaticHelper::setBaseUrl($this->getRequest(), $base_url);

    $request_preparer->prepareForRequest();
    try {
      $invoke_paths = $static->requestPath($path);
    }
    catch (\Exception $e) {
      $invoke_paths = [];
    }


    // The remaining invoke paths need to be handled in new requests.
    foreach ($invoke_paths as $path) {
      // Since we are only trying to export one path, restrict new requests to
      // paths with extensions, which are probably RSS feeds and image derivatives.
      if (pathinfo($path, PATHINFO_EXTENSION)) {
        $request_preparer->prepareForRequest();
        // This could return more paths, but we're ignoring that for simplicity.
        $static->requestPath($path);
      }
    }
    
    ```

**Comment by yuseferi** [comment]
I

**Comment by yuseferi** [comment]
I played with solution and I've got this solution


```
    /** @var \Drupal\tome_static\StaticGeneratorInterface $static */
    $static = \Drupal::service('tome_static.generator');

    /** @var \Drupal\tome_static\RequestPreparer $request_preparer */
    $request_preparer = \Drupal::service('tome_static.request_preparer');


    $path = '/en/viewport/EssDr/english/essential-drugs-16682376.html';
//    $invoke_paths = $static->requestPath($path);

    $base_url = "http://localhost:8080";

    $original_params = TomeStaticHelper::setBaseUrl($this->getRequest(), $base_url);

    $request_preparer->prepareForRequest();
    try {
      $invoke_paths = $static->requestPath($path);
    }
    catch (\Exception $e) {
      $invoke_paths = [];
    }


    // The remaining invoke paths need to be handled in new requests.
    foreach ($invoke_paths as $path) {
      // Since we are only trying to export one path, restrict new requests to
      // paths with extensions, which are probably RSS feeds and image derivatives.
      if (pathinfo($path, PATHINFO_EXTENSION)) {
        $request_preparer->prepareForRequest();
        // This could return more paths, but we're ignoring that for simplicity.
        $static->requestPath($path);
      }
    }
    
    
```

it saved HTML with correct  `base_url` replacement, the only problem is that it does not fetch and store assets files( js, CSS, image).

any thought?

**Comment by yuseferi** [comment]
just for record and maybe someone looking for the same solution: 

```
$base_url = "http://localhost:8080";
    $path = 'path_for_download';
    /** @var \Drupal\tome_static\StaticGeneratorInterface $static */
    $static = \Drupal::service('tome_static.generator');

    /** @var \Drupal\tome_static\RequestPreparer $request_preparer */
    $request_preparer = \Drupal::service('tome_static.request_preparer');

    $original_params = TomeStaticHelper::setBaseUrl($this->getRequest(), $base_url);

    // Prepare for a new request. This is necessary so that static caches in Drupal
    // can be reset between multiple requests in one bootstrap.
    $request_preparer->prepareForRequest();

    // Request an arbitrary path. "$invoke_paths" at this point is anything that
    // needs to be copied (an existing file) or requested (an image derivative,
    // other paths, etc.)

    $invoke_paths = $static->requestPath($path);

    // Export paths will try to copy or remove as many paths as possible without
    // making a new internal request.
    $invoke_paths = $static->exportPaths($invoke_paths);
//    $static->requestPath($path);
//    dump($invoke_paths);

    // The remaining invoke paths need to be handled in new requests.
    foreach ($invoke_paths as $path) {
      // Since we are only trying to export one path, restrict new requests to
      // paths with extensions, which are probably RSS feeds and image derivatives.
      if (pathinfo($path, PATHINFO_EXTENSION)) {
        $request_preparer->prepareForRequest();
        // This could return more paths, but we're ignoring that for simplicity.
        $static->requestPath($path);
      }
    }
```

Thanks a lot.
