### ISSUE TITLE
Rename init and install commands?

### ISSUE THREAD

**Issue by gitressa** [drupal-tome/tome-project#15]
**Describe the bug**
I was testing Bookish, and following the [instructions](https://github.com/drupal-tome/bookish#install-with-tome) I got tricked by the naming of the commands. I thought I had to run both `drush tome:init` as well as `drush tome:install`.

In my mind, `init` signifies setting some defaults, but not installing. Also, it says:
> To re-install your site, run:
> `drush tome:install`

I don't know if it would require a lot of work (or even possible) but is it worth considering these changes?
1. Rename `tome:init` to `tome:install`
1. Rename `tome:install` to `tome:rebuild` or `tome:re-install`

If it's too late by now, I understand, I thought I'd just share my 2 cents :-)

**Comment by mortenson** [comment]
It's too late to rename the commands due to backwards compatibility, but maybe I can edit the Bookish README so that the note about "re-installing" comes later? Like "If you ever need to re-install your site..."

**Comment by gitressa** [comment]
Ah yes, that's what I thought. Perhaps I can create a pull request with a suggestion on how to outline the needed steps?

**Comment by mortenson** [comment]
Sure! A PR to Bookish sounds good.

**Comment by gitressa** [comment]
Great! I have created a PR which updates the README. I also added a Lando section, I hope it's al right? It is after all the most popular Developer environment. Maybe a DDEV section could also be added, by a more experienced DDEV user?
