### ISSUE TITLE
Main Index page gets generated then regenerated with only redirect

### ISSUE THREAD

**Issue by arafalov** [drupal-tome/tome-project#9]
I am trying this on a large (and messy) Drupal 8 site and it looks great so far. 

The one issue I am running into is that main index.html generates a redirect. But, somehow, right at the end. As in, it generates full index.html file. Then at some point in the build, it regenerates it with the file that does a redirect to https version of the site.

Interestingly, if I rename/delete generated index.html and rerun the command, it generates the full version of that file. So, it is definitely something in the process.

The command I tested with is: `drush tome:static --uri=http://prodsite.example` inside a DDev container. I am quite sure the canonical url that Tome sees is https version.

I am guessing it is something with my site (maybe something links to non-http version of the home page and tome regenerates it?). I am not able to reproduce the issue on an new test site.

I am not sure how to troubleshoot this further. Is there a debug flag or something else I can run to figure it out?

**Comment by mortenson** [comment]
@arafalov Thanks for reaching out! Could you file an issue for this at https://drupal.org/project/tome ? It's easier to track things over there. I think there might also be an issue and patch for this as well, please see https://www.drupal.org/project/tome/issues/3120435 . If that works for you, feel free to comment or even RTBC.

For debugging, there is a `-v` flag, and also `tome:static-export-path` which would let you run a lower level command. Beyond that XDebug/print statements at different points in the static generation and Drush process is your best option.

**Comment by arafalov** [comment]
The linked issue was a good match and the patch worked for me. Left a comment there, as requested. Did not change the status, as I am not sure my informal test is sufficient. But it seems to work.
